[package]
name = "gwstuff"
version = "0.0.1"
edition = "2021"

[dependencies]
font-loader = "0.11.0"
smithay-client-toolkit = "0.15.4"
rusttype = "0.9.2"
toml = "0.5.9"
serde_derive = "1.0.137"
serde = "1.0.137"
whoami = "1.2.1"
