[window]
width  = '100'
height = '100'
background_color = '0x262626'
win_position = 'CENTER_VERTICAL, CENTER_HORIZONTAL'

[margins]
vertical_percentage   = '10'
horizontal_percentage = '10'

[font]
name  = 'Roboto Condensed'
size  = '15'
color = '0x808080'
